# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageShareExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageShareExtension
pod 'Moya', '~> 15.0'
pod 'IQKeyboardManagerSwift'
pod 'Toast-Swift', '~> 5.0.1'

end

target 'PhotoSurfer-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoSurfer-iOS
pod 'Moya', '~> 15.0'
pod 'IQKeyboardManagerSwift'
pod 'Kingfisher', '~> 7.0'
pod 'lottie-ios'
pod 'Toast-Swift', '~> 5.0.1'

end
